// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/draft.proto

package draft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for requests/responses with no data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_draft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{0}
}

// Player message
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Team          string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	Points        int32                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	Tier          string                 `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`
	Drafted       bool                   `protobuf:"varint,7,opt,name=drafted,proto3" json:"drafted,omitempty"`
	DraftedBy     string                 `protobuf:"bytes,8,opt,name=drafted_by,json=draftedBy,proto3" json:"drafted_by,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_draft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Player) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Player) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Player) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Player) GetDrafted() bool {
	if x != nil {
		return x.Drafted
	}
	return false
}

func (x *Player) GetDraftedBy() string {
	if x != nil {
		return x.DraftedBy
	}
	return ""
}

func (x *Player) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Team message
type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Mascot        string                 `protobuf:"bytes,4,opt,name=mascot,proto3" json:"mascot,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Players       []*Player              `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_proto_draft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{2}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Team) GetMascot() string {
	if x != nil {
		return x.Mascot
	}
	return ""
}

func (x *Team) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Team) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// ChatMessage message
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Emotes        map[string]int32       `protobuf:"bytes,5,rep,name=emotes,proto3" json:"emotes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_draft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ChatMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetEmotes() map[string]int32 {
	if x != nil {
		return x.Emotes
	}
	return nil
}

// DraftState message
type DraftState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Teams         []*Team                `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	Chat          []*ChatMessage         `protobuf:"bytes,3,rep,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftState) Reset() {
	*x = DraftState{}
	mi := &file_proto_draft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftState) ProtoMessage() {}

func (x *DraftState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftState.ProtoReflect.Descriptor instead.
func (*DraftState) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{4}
}

func (x *DraftState) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *DraftState) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *DraftState) GetChat() []*ChatMessage {
	if x != nil {
		return x.Chat
	}
	return nil
}

// DraftPlayerRequest message
type DraftPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftPlayerRequest) Reset() {
	*x = DraftPlayerRequest{}
	mi := &file_proto_draft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftPlayerRequest) ProtoMessage() {}

func (x *DraftPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftPlayerRequest.ProtoReflect.Descriptor instead.
func (*DraftPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{5}
}

func (x *DraftPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DraftPlayerRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// DraftPlayerResponse message
type DraftPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftPlayerResponse) Reset() {
	*x = DraftPlayerResponse{}
	mi := &file_proto_draft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftPlayerResponse) ProtoMessage() {}

func (x *DraftPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftPlayerResponse.ProtoReflect.Descriptor instead.
func (*DraftPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{6}
}

func (x *DraftPlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// AddTeamRequest message
type AddTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Mascot        string                 `protobuf:"bytes,3,opt,name=mascot,proto3" json:"mascot,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamRequest) Reset() {
	*x = AddTeamRequest{}
	mi := &file_proto_draft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamRequest) ProtoMessage() {}

func (x *AddTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamRequest.ProtoReflect.Descriptor instead.
func (*AddTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{7}
}

func (x *AddTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTeamRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AddTeamRequest) GetMascot() string {
	if x != nil {
		return x.Mascot
	}
	return ""
}

func (x *AddTeamRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// TeamsResponse message
type TeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamsResponse) Reset() {
	*x = TeamsResponse{}
	mi := &file_proto_draft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsResponse) ProtoMessage() {}

func (x *TeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsResponse.ProtoReflect.Descriptor instead.
func (*TeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{8}
}

func (x *TeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

// ReorderTeamsRequest message
type ReorderTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         []string               `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderTeamsRequest) Reset() {
	*x = ReorderTeamsRequest{}
	mi := &file_proto_draft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderTeamsRequest) ProtoMessage() {}

func (x *ReorderTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderTeamsRequest.ProtoReflect.Descriptor instead.
func (*ReorderTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{9}
}

func (x *ReorderTeamsRequest) GetOrder() []string {
	if x != nil {
		return x.Order
	}
	return nil
}

// SetPlayerPointsRequest message
type SetPlayerPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerPointsRequest) Reset() {
	*x = SetPlayerPointsRequest{}
	mi := &file_proto_draft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerPointsRequest) ProtoMessage() {}

func (x *SetPlayerPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerPointsRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerPointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{10}
}

func (x *SetPlayerPointsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetPlayerPointsRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// GetPlayerProfileRequest message
type GetPlayerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerProfileRequest) Reset() {
	*x = GetPlayerProfileRequest{}
	mi := &file_proto_draft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerProfileRequest) ProtoMessage() {}

func (x *GetPlayerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlayerProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// PlayerProfile message
type PlayerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Team          string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	Points        int32                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	Tier          string                 `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`
	Drafted       bool                   `protobuf:"varint,7,opt,name=drafted,proto3" json:"drafted,omitempty"`
	DraftedBy     string                 `protobuf:"bytes,8,opt,name=drafted_by,json=draftedBy,proto3" json:"drafted_by,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Metrics       *PlayerMetrics         `protobuf:"bytes,10,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	mi := &file_proto_draft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerProfile) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *PlayerProfile) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *PlayerProfile) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *PlayerProfile) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *PlayerProfile) GetDrafted() bool {
	if x != nil {
		return x.Drafted
	}
	return false
}

func (x *PlayerProfile) GetDraftedBy() string {
	if x != nil {
		return x.DraftedBy
	}
	return ""
}

func (x *PlayerProfile) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PlayerProfile) GetMetrics() *PlayerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// PlayerMetrics message
type PlayerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   int32                  `protobuf:"varint,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Popularity    int32                  `protobuf:"varint,2,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Efficiency    int32                  `protobuf:"varint,3,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	TrendDelta    float64                `protobuf:"fixed64,4,opt,name=trend_delta,json=trendDelta,proto3" json:"trend_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMetrics) Reset() {
	*x = PlayerMetrics{}
	mi := &file_proto_draft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMetrics) ProtoMessage() {}

func (x *PlayerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMetrics.ProtoReflect.Descriptor instead.
func (*PlayerMetrics) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerMetrics) GetConsistency() int32 {
	if x != nil {
		return x.Consistency
	}
	return 0
}

func (x *PlayerMetrics) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *PlayerMetrics) GetEfficiency() int32 {
	if x != nil {
		return x.Efficiency
	}
	return 0
}

func (x *PlayerMetrics) GetTrendDelta() float64 {
	if x != nil {
		return x.TrendDelta
	}
	return 0
}

// ChatResponse message
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_draft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{14}
}

func (x *ChatResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// SendChatRequest message
type SendChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatRequest) Reset() {
	*x = SendChatRequest{}
	mi := &file_proto_draft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatRequest) ProtoMessage() {}

func (x *SendChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatRequest.ProtoReflect.Descriptor instead.
func (*SendChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{15}
}

func (x *SendChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendChatRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// AddReactionRequest message
type AddReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Emote         string                 `protobuf:"bytes,2,opt,name=emote,proto3" json:"emote,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionRequest) Reset() {
	*x = AddReactionRequest{}
	mi := &file_proto_draft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionRequest) ProtoMessage() {}

func (x *AddReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionRequest.ProtoReflect.Descriptor instead.
func (*AddReactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{16}
}

func (x *AddReactionRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AddReactionRequest) GetEmote() string {
	if x != nil {
		return x.Emote
	}
	return ""
}

func (x *AddReactionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Event message for streaming
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_draft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_draft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_draft_proto_rawDescGZIP(), []int{17}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_draft_proto protoreflect.FileDescriptor

const file_proto_draft_proto_rawDesc = "" +
	"\n" +
	"\x11proto/draft.proto\x12\x05draft\"\a\n" +
	"\x05Empty\"\xd7\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x05R\x06points\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\tR\x04tier\x12\x18\n" +
	"\adrafted\x18\a \x01(\bR\adrafted\x12\x1d\n" +
	"\n" +
	"drafted_by\x18\b \x01(\tR\tdraftedBy\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\"\x97\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06mascot\x18\x04 \x01(\tR\x06mascot\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12'\n" +
	"\aplayers\x18\x06 \x03(\v2\r.draft.PlayerR\aplayers\"\xc8\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x126\n" +
	"\x06emotes\x18\x05 \x03(\v2\x1e.draft.ChatMessage.EmotesEntryR\x06emotes\x1a9\n" +
	"\vEmotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x80\x01\n" +
	"\n" +
	"DraftState\x12'\n" +
	"\aplayers\x18\x01 \x03(\v2\r.draft.PlayerR\aplayers\x12!\n" +
	"\x05teams\x18\x02 \x03(\v2\v.draft.TeamR\x05teams\x12&\n" +
	"\x04chat\x18\x03 \x03(\v2\x12.draft.ChatMessageR\x04chat\"J\n" +
	"\x12DraftPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\"/\n" +
	"\x13DraftPlayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"h\n" +
	"\x0eAddTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x16\n" +
	"\x06mascot\x18\x03 \x01(\tR\x06mascot\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"2\n" +
	"\rTeamsResponse\x12!\n" +
	"\x05teams\x18\x01 \x03(\v2\v.draft.TeamR\x05teams\"+\n" +
	"\x13ReorderTeamsRequest\x12\x14\n" +
	"\x05order\x18\x01 \x03(\tR\x05order\"@\n" +
	"\x16SetPlayerPointsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\")\n" +
	"\x17GetPlayerProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8e\x02\n" +
	"\rPlayerProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x05R\x06points\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\tR\x04tier\x12\x18\n" +
	"\adrafted\x18\a \x01(\bR\adrafted\x12\x1d\n" +
	"\n" +
	"drafted_by\x18\b \x01(\tR\tdraftedBy\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12.\n" +
	"\ametrics\x18\n" +
	" \x01(\v2\x14.draft.PlayerMetricsR\ametrics\"\x92\x01\n" +
	"\rPlayerMetrics\x12 \n" +
	"\vconsistency\x18\x01 \x01(\x05R\vconsistency\x12\x1e\n" +
	"\n" +
	"popularity\x18\x02 \x01(\x05R\n" +
	"popularity\x12\x1e\n" +
	"\n" +
	"efficiency\x18\x03 \x01(\x05R\n" +
	"efficiency\x12\x1f\n" +
	"\vtrend_delta\x18\x04 \x01(\x01R\n" +
	"trendDelta\">\n" +
	"\fChatResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.draft.ChatMessageR\bmessages\"9\n" +
	"\x0fSendChatRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"]\n" +
	"\x12AddReactionRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05emote\x18\x02 \x01(\tR\x05emote\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"\x8c\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x123\n" +
	"\apayload\x18\x02 \x03(\v2\x19.draft.Event.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdd\x05\n" +
	"\fDraftService\x12+\n" +
	"\bGetState\x12\f.draft.Empty\x1a\x11.draft.DraftState\x12D\n" +
	"\vDraftPlayer\x12\x19.draft.DraftPlayerRequest\x1a\x1a.draft.DraftPlayerResponse\x12(\n" +
	"\n" +
	"ResetDraft\x12\f.draft.Empty\x1a\f.draft.Empty\x12-\n" +
	"\aAddTeam\x12\x15.draft.AddTeamRequest\x1a\v.draft.Team\x12/\n" +
	"\tListTeams\x12\f.draft.Empty\x1a\x14.draft.TeamsResponse\x12@\n" +
	"\fReorderTeams\x12\x1a.draft.ReorderTeamsRequest\x1a\x14.draft.TeamsResponse\x12)\n" +
	"\tAddPlayer\x12\r.draft.Player\x1a\r.draft.Player\x12?\n" +
	"\x0fSetPlayerPoints\x12\x1d.draft.SetPlayerPointsRequest\x1a\r.draft.Player\x12H\n" +
	"\x10GetPlayerProfile\x12\x1e.draft.GetPlayerProfileRequest\x1a\x14.draft.PlayerProfile\x12-\n" +
	"\bListChat\x12\f.draft.Empty\x1a\x13.draft.ChatResponse\x12=\n" +
	"\x0fSendChatMessage\x12\x16.draft.SendChatRequest\x1a\x12.draft.ChatMessage\x12<\n" +
	"\vAddReaction\x12\x19.draft.AddReactionRequest\x1a\x12.draft.ChatMessage\x12,\n" +
	"\fStreamEvents\x12\f.draft.Empty\x1a\f.draft.Event0\x01B9Z7github.com/Billy-Davies-2/jellycat-draft-ui/proto;draftb\x06proto3"

var (
	file_proto_draft_proto_rawDescOnce sync.Once
	file_proto_draft_proto_rawDescData []byte
)

func file_proto_draft_proto_rawDescGZIP() []byte {
	file_proto_draft_proto_rawDescOnce.Do(func() {
		file_proto_draft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_draft_proto_rawDesc), len(file_proto_draft_proto_rawDesc)))
	})
	return file_proto_draft_proto_rawDescData
}

var file_proto_draft_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_draft_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: draft.Empty
	(*Player)(nil),                  // 1: draft.Player
	(*Team)(nil),                    // 2: draft.Team
	(*ChatMessage)(nil),             // 3: draft.ChatMessage
	(*DraftState)(nil),              // 4: draft.DraftState
	(*DraftPlayerRequest)(nil),      // 5: draft.DraftPlayerRequest
	(*DraftPlayerResponse)(nil),     // 6: draft.DraftPlayerResponse
	(*AddTeamRequest)(nil),          // 7: draft.AddTeamRequest
	(*TeamsResponse)(nil),           // 8: draft.TeamsResponse
	(*ReorderTeamsRequest)(nil),     // 9: draft.ReorderTeamsRequest
	(*SetPlayerPointsRequest)(nil),  // 10: draft.SetPlayerPointsRequest
	(*GetPlayerProfileRequest)(nil), // 11: draft.GetPlayerProfileRequest
	(*PlayerProfile)(nil),           // 12: draft.PlayerProfile
	(*PlayerMetrics)(nil),           // 13: draft.PlayerMetrics
	(*ChatResponse)(nil),            // 14: draft.ChatResponse
	(*SendChatRequest)(nil),         // 15: draft.SendChatRequest
	(*AddReactionRequest)(nil),      // 16: draft.AddReactionRequest
	(*Event)(nil),                   // 17: draft.Event
	nil,                             // 18: draft.ChatMessage.EmotesEntry
	nil,                             // 19: draft.Event.PayloadEntry
}
var file_proto_draft_proto_depIdxs = []int32{
	1,  // 0: draft.Team.players:type_name -> draft.Player
	18, // 1: draft.ChatMessage.emotes:type_name -> draft.ChatMessage.EmotesEntry
	1,  // 2: draft.DraftState.players:type_name -> draft.Player
	2,  // 3: draft.DraftState.teams:type_name -> draft.Team
	3,  // 4: draft.DraftState.chat:type_name -> draft.ChatMessage
	2,  // 5: draft.TeamsResponse.teams:type_name -> draft.Team
	13, // 6: draft.PlayerProfile.metrics:type_name -> draft.PlayerMetrics
	3,  // 7: draft.ChatResponse.messages:type_name -> draft.ChatMessage
	19, // 8: draft.Event.payload:type_name -> draft.Event.PayloadEntry
	0,  // 9: draft.DraftService.GetState:input_type -> draft.Empty
	5,  // 10: draft.DraftService.DraftPlayer:input_type -> draft.DraftPlayerRequest
	0,  // 11: draft.DraftService.ResetDraft:input_type -> draft.Empty
	7,  // 12: draft.DraftService.AddTeam:input_type -> draft.AddTeamRequest
	0,  // 13: draft.DraftService.ListTeams:input_type -> draft.Empty
	9,  // 14: draft.DraftService.ReorderTeams:input_type -> draft.ReorderTeamsRequest
	1,  // 15: draft.DraftService.AddPlayer:input_type -> draft.Player
	10, // 16: draft.DraftService.SetPlayerPoints:input_type -> draft.SetPlayerPointsRequest
	11, // 17: draft.DraftService.GetPlayerProfile:input_type -> draft.GetPlayerProfileRequest
	0,  // 18: draft.DraftService.ListChat:input_type -> draft.Empty
	15, // 19: draft.DraftService.SendChatMessage:input_type -> draft.SendChatRequest
	16, // 20: draft.DraftService.AddReaction:input_type -> draft.AddReactionRequest
	0,  // 21: draft.DraftService.StreamEvents:input_type -> draft.Empty
	4,  // 22: draft.DraftService.GetState:output_type -> draft.DraftState
	6,  // 23: draft.DraftService.DraftPlayer:output_type -> draft.DraftPlayerResponse
	0,  // 24: draft.DraftService.ResetDraft:output_type -> draft.Empty
	2,  // 25: draft.DraftService.AddTeam:output_type -> draft.Team
	8,  // 26: draft.DraftService.ListTeams:output_type -> draft.TeamsResponse
	8,  // 27: draft.DraftService.ReorderTeams:output_type -> draft.TeamsResponse
	1,  // 28: draft.DraftService.AddPlayer:output_type -> draft.Player
	1,  // 29: draft.DraftService.SetPlayerPoints:output_type -> draft.Player
	12, // 30: draft.DraftService.GetPlayerProfile:output_type -> draft.PlayerProfile
	14, // 31: draft.DraftService.ListChat:output_type -> draft.ChatResponse
	3,  // 32: draft.DraftService.SendChatMessage:output_type -> draft.ChatMessage
	3,  // 33: draft.DraftService.AddReaction:output_type -> draft.ChatMessage
	17, // 34: draft.DraftService.StreamEvents:output_type -> draft.Event
	22, // [22:35] is the sub-list for method output_type
	9,  // [9:22] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_draft_proto_init() }
func file_proto_draft_proto_init() {
	if File_proto_draft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_draft_proto_rawDesc), len(file_proto_draft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_draft_proto_goTypes,
		DependencyIndexes: file_proto_draft_proto_depIdxs,
		MessageInfos:      file_proto_draft_proto_msgTypes,
	}.Build()
	File_proto_draft_proto = out.File
	file_proto_draft_proto_goTypes = nil
	file_proto_draft_proto_depIdxs = nil
}
