// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/draft.proto

package draft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DraftService_GetState_FullMethodName         = "/draft.DraftService/GetState"
	DraftService_DraftPlayer_FullMethodName      = "/draft.DraftService/DraftPlayer"
	DraftService_ResetDraft_FullMethodName       = "/draft.DraftService/ResetDraft"
	DraftService_AddTeam_FullMethodName          = "/draft.DraftService/AddTeam"
	DraftService_ListTeams_FullMethodName        = "/draft.DraftService/ListTeams"
	DraftService_ReorderTeams_FullMethodName     = "/draft.DraftService/ReorderTeams"
	DraftService_AddPlayer_FullMethodName        = "/draft.DraftService/AddPlayer"
	DraftService_SetPlayerPoints_FullMethodName  = "/draft.DraftService/SetPlayerPoints"
	DraftService_GetPlayerProfile_FullMethodName = "/draft.DraftService/GetPlayerProfile"
	DraftService_ListChat_FullMethodName         = "/draft.DraftService/ListChat"
	DraftService_SendChatMessage_FullMethodName  = "/draft.DraftService/SendChatMessage"
	DraftService_AddReaction_FullMethodName      = "/draft.DraftService/AddReaction"
	DraftService_StreamEvents_FullMethodName     = "/draft.DraftService/StreamEvents"
)

// DraftServiceClient is the client API for DraftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Draft service provides all draft-related operations
type DraftServiceClient interface {
	// Get current draft state
	GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DraftState, error)
	// Draft a player to a team
	DraftPlayer(ctx context.Context, in *DraftPlayerRequest, opts ...grpc.CallOption) (*DraftPlayerResponse, error)
	// Reset the draft
	ResetDraft(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Add a new team
	AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*Team, error)
	// List all teams
	ListTeams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TeamsResponse, error)
	// Reorder teams
	ReorderTeams(ctx context.Context, in *ReorderTeamsRequest, opts ...grpc.CallOption) (*TeamsResponse, error)
	// Add a new player
	AddPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error)
	// Set player points
	SetPlayerPoints(ctx context.Context, in *SetPlayerPointsRequest, opts ...grpc.CallOption) (*Player, error)
	// Get player profile
	GetPlayerProfile(ctx context.Context, in *GetPlayerProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error)
	// List chat messages
	ListChat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChatResponse, error)
	// Send chat message
	SendChatMessage(ctx context.Context, in *SendChatRequest, opts ...grpc.CallOption) (*ChatMessage, error)
	// Add reaction to chat message
	AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*ChatMessage, error)
	// Stream events (replaces SSE)
	StreamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type draftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDraftServiceClient(cc grpc.ClientConnInterface) DraftServiceClient {
	return &draftServiceClient{cc}
}

func (c *draftServiceClient) GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DraftState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftState)
	err := c.cc.Invoke(ctx, DraftService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) DraftPlayer(ctx context.Context, in *DraftPlayerRequest, opts ...grpc.CallOption) (*DraftPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftPlayerResponse)
	err := c.cc.Invoke(ctx, DraftService_DraftPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) ResetDraft(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DraftService_ResetDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) AddTeam(ctx context.Context, in *AddTeamRequest, opts ...grpc.CallOption) (*Team, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Team)
	err := c.cc.Invoke(ctx, DraftService_AddTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) ListTeams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeamsResponse)
	err := c.cc.Invoke(ctx, DraftService_ListTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) ReorderTeams(ctx context.Context, in *ReorderTeamsRequest, opts ...grpc.CallOption) (*TeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeamsResponse)
	err := c.cc.Invoke(ctx, DraftService_ReorderTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) AddPlayer(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Player)
	err := c.cc.Invoke(ctx, DraftService_AddPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) SetPlayerPoints(ctx context.Context, in *SetPlayerPointsRequest, opts ...grpc.CallOption) (*Player, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Player)
	err := c.cc.Invoke(ctx, DraftService_SetPlayerPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) GetPlayerProfile(ctx context.Context, in *GetPlayerProfileRequest, opts ...grpc.CallOption) (*PlayerProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerProfile)
	err := c.cc.Invoke(ctx, DraftService_GetPlayerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) ListChat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, DraftService_ListChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) SendChatMessage(ctx context.Context, in *SendChatRequest, opts ...grpc.CallOption) (*ChatMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessage)
	err := c.cc.Invoke(ctx, DraftService_SendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) AddReaction(ctx context.Context, in *AddReactionRequest, opts ...grpc.CallOption) (*ChatMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessage)
	err := c.cc.Invoke(ctx, DraftService_AddReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *draftServiceClient) StreamEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DraftService_ServiceDesc.Streams[0], DraftService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DraftService_StreamEventsClient = grpc.ServerStreamingClient[Event]

// DraftServiceServer is the server API for DraftService service.
// All implementations must embed UnimplementedDraftServiceServer
// for forward compatibility.
//
// Draft service provides all draft-related operations
type DraftServiceServer interface {
	// Get current draft state
	GetState(context.Context, *Empty) (*DraftState, error)
	// Draft a player to a team
	DraftPlayer(context.Context, *DraftPlayerRequest) (*DraftPlayerResponse, error)
	// Reset the draft
	ResetDraft(context.Context, *Empty) (*Empty, error)
	// Add a new team
	AddTeam(context.Context, *AddTeamRequest) (*Team, error)
	// List all teams
	ListTeams(context.Context, *Empty) (*TeamsResponse, error)
	// Reorder teams
	ReorderTeams(context.Context, *ReorderTeamsRequest) (*TeamsResponse, error)
	// Add a new player
	AddPlayer(context.Context, *Player) (*Player, error)
	// Set player points
	SetPlayerPoints(context.Context, *SetPlayerPointsRequest) (*Player, error)
	// Get player profile
	GetPlayerProfile(context.Context, *GetPlayerProfileRequest) (*PlayerProfile, error)
	// List chat messages
	ListChat(context.Context, *Empty) (*ChatResponse, error)
	// Send chat message
	SendChatMessage(context.Context, *SendChatRequest) (*ChatMessage, error)
	// Add reaction to chat message
	AddReaction(context.Context, *AddReactionRequest) (*ChatMessage, error)
	// Stream events (replaces SSE)
	StreamEvents(*Empty, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedDraftServiceServer()
}

// UnimplementedDraftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDraftServiceServer struct{}

func (UnimplementedDraftServiceServer) GetState(context.Context, *Empty) (*DraftState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedDraftServiceServer) DraftPlayer(context.Context, *DraftPlayerRequest) (*DraftPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DraftPlayer not implemented")
}
func (UnimplementedDraftServiceServer) ResetDraft(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDraft not implemented")
}
func (UnimplementedDraftServiceServer) AddTeam(context.Context, *AddTeamRequest) (*Team, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTeam not implemented")
}
func (UnimplementedDraftServiceServer) ListTeams(context.Context, *Empty) (*TeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeams not implemented")
}
func (UnimplementedDraftServiceServer) ReorderTeams(context.Context, *ReorderTeamsRequest) (*TeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderTeams not implemented")
}
func (UnimplementedDraftServiceServer) AddPlayer(context.Context, *Player) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlayer not implemented")
}
func (UnimplementedDraftServiceServer) SetPlayerPoints(context.Context, *SetPlayerPointsRequest) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlayerPoints not implemented")
}
func (UnimplementedDraftServiceServer) GetPlayerProfile(context.Context, *GetPlayerProfileRequest) (*PlayerProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerProfile not implemented")
}
func (UnimplementedDraftServiceServer) ListChat(context.Context, *Empty) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChat not implemented")
}
func (UnimplementedDraftServiceServer) SendChatMessage(context.Context, *SendChatRequest) (*ChatMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedDraftServiceServer) AddReaction(context.Context, *AddReactionRequest) (*ChatMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReaction not implemented")
}
func (UnimplementedDraftServiceServer) StreamEvents(*Empty, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDraftServiceServer) mustEmbedUnimplementedDraftServiceServer() {}
func (UnimplementedDraftServiceServer) testEmbeddedByValue()                      {}

// UnsafeDraftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DraftServiceServer will
// result in compilation errors.
type UnsafeDraftServiceServer interface {
	mustEmbedUnimplementedDraftServiceServer()
}

func RegisterDraftServiceServer(s grpc.ServiceRegistrar, srv DraftServiceServer) {
	// If the following call pancis, it indicates UnimplementedDraftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DraftService_ServiceDesc, srv)
}

func _DraftService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).GetState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_DraftPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DraftPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).DraftPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_DraftPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).DraftPlayer(ctx, req.(*DraftPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_ResetDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).ResetDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_ResetDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).ResetDraft(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_AddTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).AddTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_AddTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).AddTeam(ctx, req.(*AddTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_ListTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).ListTeams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_ReorderTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).ReorderTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_ReorderTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).ReorderTeams(ctx, req.(*ReorderTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_AddPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).AddPlayer(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_SetPlayerPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).SetPlayerPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_SetPlayerPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).SetPlayerPoints(ctx, req.(*SetPlayerPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_GetPlayerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).GetPlayerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_GetPlayerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).GetPlayerProfile(ctx, req.(*GetPlayerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_ListChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).ListChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_ListChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).ListChat(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_SendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).SendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_SendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).SendChatMessage(ctx, req.(*SendChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_AddReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DraftServiceServer).AddReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DraftService_AddReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DraftServiceServer).AddReaction(ctx, req.(*AddReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DraftService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DraftServiceServer).StreamEvents(m, &grpc.GenericServerStream[Empty, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DraftService_StreamEventsServer = grpc.ServerStreamingServer[Event]

// DraftService_ServiceDesc is the grpc.ServiceDesc for DraftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DraftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "draft.DraftService",
	HandlerType: (*DraftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _DraftService_GetState_Handler,
		},
		{
			MethodName: "DraftPlayer",
			Handler:    _DraftService_DraftPlayer_Handler,
		},
		{
			MethodName: "ResetDraft",
			Handler:    _DraftService_ResetDraft_Handler,
		},
		{
			MethodName: "AddTeam",
			Handler:    _DraftService_AddTeam_Handler,
		},
		{
			MethodName: "ListTeams",
			Handler:    _DraftService_ListTeams_Handler,
		},
		{
			MethodName: "ReorderTeams",
			Handler:    _DraftService_ReorderTeams_Handler,
		},
		{
			MethodName: "AddPlayer",
			Handler:    _DraftService_AddPlayer_Handler,
		},
		{
			MethodName: "SetPlayerPoints",
			Handler:    _DraftService_SetPlayerPoints_Handler,
		},
		{
			MethodName: "GetPlayerProfile",
			Handler:    _DraftService_GetPlayerProfile_Handler,
		},
		{
			MethodName: "ListChat",
			Handler:    _DraftService_ListChat_Handler,
		},
		{
			MethodName: "SendChatMessage",
			Handler:    _DraftService_SendChatMessage_Handler,
		},
		{
			MethodName: "AddReaction",
			Handler:    _DraftService_AddReaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _DraftService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/draft.proto",
}
